// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCcTLDOOhnzaRhsdfcD6g8gaIWdHMiDB_g',
    appId: '1:728447659284:web:0e526347dd2bc55b0f2601',
    messagingSenderId: '728447659284',
    projectId: 'majorproject-c5c5f',
    authDomain: 'majorproject-c5c5f.firebaseapp.com',
    storageBucket: 'majorproject-c5c5f.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDy7JDqtGcK9dNW5sTNg_H2k2N7_u_xSLg',
    appId: '1:728447659284:android:259b9dca6914ef010f2601',
    messagingSenderId: '728447659284',
    projectId: 'majorproject-c5c5f',
    storageBucket: 'majorproject-c5c5f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDVcyMt-AisPpHq5vK2x72qqiKww_Mqdi0',
    appId: '1:728447659284:ios:aa35d7db2820b20e0f2601',
    messagingSenderId: '728447659284',
    projectId: 'majorproject-c5c5f',
    storageBucket: 'majorproject-c5c5f.appspot.com',
    iosBundleId: 'com.example.mealsapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDVcyMt-AisPpHq5vK2x72qqiKww_Mqdi0',
    appId: '1:728447659284:ios:e6a24570d51d4ce50f2601',
    messagingSenderId: '728447659284',
    projectId: 'majorproject-c5c5f',
    storageBucket: 'majorproject-c5c5f.appspot.com',
    iosBundleId: 'com.example.mealsapp.RunnerTests',
  );
}
